#!/bin/bash

#Color
DF='\e[39m'
Bold='\e[1m'
Blink='\e[5m'
yell='\e[33m'
RED='\033[0;31m'
green='\e[32m'
BEREMRED='\033[38;5;197m'
cyan='\e[36m'
LRED='\e[91m'
Lgreen='\e[92m'
Lyellow='\e[93m'
NC='\e[0m'
GREEN='\033[0;32m'
ORANGE='\033[0;33m'
LIGHT='\033[0;37m'
grenbo="\e[92;1m"
blue="\033[0;34m"
Blue="\033[36m"
BIRUKOLOT="\033[38;5;111m"
clear


# // System Information
domain=$(cat /etc/xray/domain)
WKT=$(curl -s ipinfo.io/timezone)
IPVPS=$(curl -s ipv4.icanhazip.com)
tram=$(free -m | awk 'NR==2 {print $2}')
swap=$(free -m | awk 'NR==4 {print $2}')
freq=$(awk -F: ' /cpu MHz/ {freq=$2} END {print freq}' /proc/cpuinfo)
cores=$(awk -F: '/model name/ {core++} END {print core}' /proc/cpuinfo)
cname=$(awk -F: '/model name/ {name=$2} END {print name}' /proc/cpuinfo)
knr=$( uname -r )

# // Exporting IP Address
export IP=$( curl -s https://ipinfo.io/ip/ )
# // SSH
ssh_service=$(/etc/init.d/ssh status | grep Active | awk '{print $3}' | cut -d "(" -f2 | cut -d ")" -f1)
openvpn_service="$(systemctl show openvpn.service --no-page)"
oovpn=$(echo "${openvpn_service}" | grep 'ActiveState=' | cut -f2 -d=)
dropbear_status=$(/etc/init.d/dropbear status | grep Active | awk '{print $3}' | cut -d "(" -f2 | cut -d ")" -f1)
haproxy_service=$(systemctl status haproxy | grep Active | awk '{print $3}' | cut -d "(" -f2 | cut -d ")" -f1)
#fail2ban_service=$(/etc/init.d/fail2ban status | grep Active | awk '{print $3}' | cut -d "(" -f2 | cut -d ")" -f1)
cron_service=$(systemctl  status cron | grep Active | awk '{print $3}' | cut -d "(" -f2 | cut -d ")" -f1)
badvpn1=$(systemctl status udp-mini-1 | grep Active | awk '{print $3}' | cut -d "(" -f2 | cut -d ")" -f1)
badvpn2=$(systemctl status udp-mini-2 | grep Active | awk '{print $3}' | cut -d "(" -f2 | cut -d ")" -f1)
badvpn3=$(systemctl status udp-mini-3 | grep Active | awk '{print $3}' | cut -d "(" -f2 | cut -d ")" -f1)
Iptables=$(systemctl status netfilter-persistent | grep active | awk '{print $3}' | sed 's/(//g' | sed 's/)//g')
RClocal=$(systemctl status rc-local | grep active | awk '{print $3}' | sed 's/(//g' | sed 's/)//g')
Autorebot=$(systemctl status rc-local | grep active | awk '{print $3}' | sed 's/(//g' | sed 's/)//g')
UdpSSH=$(systemctl status udp-custom | grep active | awk '{print $3}' | sed 's/(//g' | sed 's/)//g')

openssh=$( systemctl status ssh | grep Active | awk '{print $3}' | sed 's/(//g' | sed 's/)//g' )
if [[ $openssh == "running" ]]; then
    status_openssh="${GREEN} [ON] $NC${BEREMRED} │$NC"
else
    status_openssh="${RED}[OFF]${NC} "
fi

# // SSH Websocket Proxy
ssh_ws=$( systemctl status ws | grep Active | awk '{print $3}' | sed 's/(//g' | sed 's/)//g' )
if [[ $ssh_ws == "running" ]]; then
    status_ws_epro="${GREEN} [ON] $NC${BEREMRED} │$NC"
else
    status_ws_epro="${RED} [OFF] ${NC} "
fi

# // Trojan Proxy
ss=$( systemctl status xray | grep Active | awk '{print $3}' | sed 's/(//g' | sed 's/)//g' )
if [[ $ss == "running" ]]; then
    status_ss="${GREEN} [ON] $NC${BEREMRED} │$NC"
else
    status_ss="${RED} [OFF] ${NC} "
fi

# // NGINX
nginx=$( /etc/init.d/nginx status | grep Active | awk '{print $3}' | sed 's/(//g' | sed 's/)//g' )
if [[ $nginx == "running" ]]; then
    status_nginx="${GREEN} [ON] $NC${BEREMRED} │$NC"
else
    status_nginx="${RED} [OFF] ${NC} "
fi

# STATUS SERVICE IPTABLES
if [[ $Iptables == "exited" ]]; then
    status_galo="${GREEN} [ON] $NC${BEREMRED} │$NC"
else
    status_galo="${RED} [OFF] ${NC}"
fi

# STATUS SERVICE  SSH 
if [[ $ssh_service == "running" ]]; then 
   status_ssh="${GREEN} [ON] $NC${BEREMRED} │$NC"
else
   status_ssh="${RED} [OFF] ${NC} "
fi

# STATUS OHP SSH
#if [[ $ohr == "running" ]]; then 
 #  sohr="${GREEN} [ON] ${NC}${NC}"
#else
 #  sohr="${RED} [OFF] ${NC} ${NC}"
#fi

# STATUS SERVICE OPENVPN
if [[ $oovpn == "active" ]]; then
  status_openvpn="${GREEN} [ON] $NC${BEREMRED} │$NC"
else
  status_openvpn="${RED} [OFF] ${NC} "
fi

# STATUS SERVICE DROPBEAR
if [[ $dropbear_status == "running" ]]; then 
   status_beruangjatuh="${GREEN} [ON] $NC${BEREMRED} │$NC"
else
   status_beruangjatuh="${RED} [OFF] ${NC} ${NC}"
fi

# STATUS SERVICE HAPROXY
if [[ $haproxy_service == "running" ]]; then 
   status_haproxy="${GREEN} [ON] $NC${BEREMRED} │$NC"
else
   status_haproxy="${RED} [OFF] ${NC} "
fi

# STATUS SERVICE  SQUID 
#if [[ $squid_service == "running" ]]; then 
  # status_squid="${GREEN} [ON] ${NC} ( No Etror )"
#else
  # status_squid="${RED} [OFF] ${NC} "
#fi

# STATUS SERVICE  FAIL2BAN 
if [[ $fail2ban_service == "running" ]]; then 
   status_fail2ban="${GREEN} [ON] $NC${BEREMRED} │$NC"
else
   status_fail2ban="${RED} [OFF] ${NC} "
fi

# STATUS SERVICE  CRONS 
if [[ $cron_service == "running" ]]; then 
   status_cron="${GREEN} [ON] $NC${BEREMRED} │$NC"
else
   status_cron="${RED} [OFF] ${NC} "
fi

# STATUS SERVICE  BADVPN 1
if [[ $badvpn1 == "running" ]]; then 
   badvpn1="${GREEN} [ON] $NC${BEREMRED} │$NC"
else
   badvpn1="${RED} [OFF] ${NC} "
fi

# STATUS SERVICE  BADVPN 2
if [[ $badvpn2 == "running" ]]; then 
   status_udp2="${GREEN} [ON] $NC${BEREMRED} │$NC"
else
   status_udp2="${RED} [OFF] ${NC} "
fi

# STATUS SERVICE  BADVPN 3
if [[ $badvpn3 == "running" ]]; then 
   status_udp3="${GREEN} [ON] $NC${BEREMRED} │$NC"
else
   status_udp3="${RED} [OFF] ${NC} "
fi

if [[ $RClocal == "exited" ]]; then
    status_galoo="${GREEN} [ON] $NC${BEREMRED} │$NC"
else
    status_galoo="${RED} [OFF] ${NC}"
fi

if [[ $Autorebot == "exited" ]]; then
    status_galooo="${GREEN} [ON] $NC${BEREMRED} │$NC"
else
    status_galooo="${RED} [OFF] ${NC}"
fi

# STATUS SERVICE  SSH UDP 
if [[ $UdpSSH == "running" ]]; then 
   status_udp="${GREEN} [ON] $NC${BEREMRED} │$NC"
else
   status_udp="${RED} [OFF] ${NC} "
fi

clear
# jalankan loading : sleep 0.9 & loading $!
loading() {
  local pid=$1
  local delay=0.1
  local spin='-\|/'

  while ps -p $pid > /dev/null; do
    local temp=${spin#?}
    printf "[%c] " "$spin"
    local spin=$temp${spin%"$temp"}
    sleep $delay
    printf "\b\b\b\b\b\b"
  done

  printf "    \b\b\b\b"
}

clear

echo -e " ${BEREMRED}│ ${BIRUKOLOT}Service SSH / TUN                 $blue:$NC $status_ssh"
sleep 0.9 & loading $!
echo -e " ${BEREMRED}│ ${BIRUKOLOT}Service SSH UDP                   $blue:$NC $status_udp"
sleep 0.9 & loading $!
echo -e " ${BEREMRED}│ ${BIRUKOLOT}Service OpenVPN SSL               $blue:$NC $status_openvpn"
sleep 0.9 & loading $!
echo -e " ${BEREMRED}│ ${BIRUKOLOT}Service WS ePRO                   $blue:$NC $status_ws_epro"
sleep 0.9 & loading $!
echo -e " ${BEREMRED}│ ${BIRUKOLOT}Service BadVPN                    $blue:$NC $badvpn1"
sleep 0.9 & loading $!
echo -e " ${BEREMRED}│ ${BIRUKOLOT}Service Dropbear                  $blue:$NC $status_beruangjatuh"
sleep 0.9 & loading $!
echo -e " ${BEREMRED}│ ${BIRUKOLOT}Service Haproxy                   $blue:$NC $status_haproxy"
sleep 0.9 & loading $!
echo -e " ${BEREMRED}│ ${BIRUKOLOT}Service Crons                     $blue:$NC $status_cron"
sleep 0.9 & loading $!
echo -e " ${BEREMRED}│ ${BIRUKOLOT}Service Nginx Webserver           $blue:$NC $status_nginx"
echo ""
read -n 1 -s -r -p "Press !! [ ENTER ] back on menu"
menu



exec bash